id: P001839
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 10:25:00.577682
source_metadata:
  id: bdr:W1KG25815
  title: བོད་སྐད། ལོ་རིམ་ལྔ་པ།
  author: ''
  volumes:
    b8b3051a62d44198a3aae330691aa1c6:
      image_group_id: I1KG25817
      title: ''
      volume_number: 1
      total_pages: 77
      base_file: v001.txt
    21cca29333d745cda31b2e00e788249c:
      image_group_id: I1KG25818
      title: ''
      volume_number: 2
      total_pages: 118
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
