id: I4CE2DEC6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T11:15:05+00:00'
last_modified: '2022-06-07T15:20:29.630979+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25815
  title: བོད་སྐད། ལོ་རིམ་ལྔ་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    0C01:
      image_group_id: I1KG25817
      title: ''
      total_pages: 77
      order: 1
      base_file: 0C01.txt
    '7199':
      image_group_id: I1KG25818
      title: ''
      total_pages: 118
      order: 2
      base_file: 7199.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
